In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
sales_df = pd.read_csv(r"C:\Users\win 11\Downloads\rossmann-store-sales\train.csv",low_memory=False)
sales_df

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1
...,...,...,...,...,...,...,...,...,...
1017204,1111,2,2013-01-01,0,0,0,0,a,1
1017205,1112,2,2013-01-01,0,0,0,0,a,1
1017206,1113,2,2013-01-01,0,0,0,0,a,1
1017207,1114,2,2013-01-01,0,0,0,0,a,1
1017208,1115,2,2013-01-01,0,0,0,0,a,1

In [3]:
stores_df = pd.read_csv(r"C:\Users\win 11\Downloads\rossmann-store-sales\store.csv")
stores_df

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1110,1111,a,a,1900.0,6.0,2014.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
1111,1112,c,c,1880.0,4.0,2006.0,0,NaN,NaN,NaN
1112,1113,a,c,9260.0,NaN,NaN,0,NaN,NaN,NaN
1113,1114,a,c,870.0,NaN,NaN,0,NaN,NaN,NaN
1114,1115,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"

In [4]:
print("sales data shape:",sales_df.shape)
print("stores data shape:",stores_df.shape)

sales data shape: (1017209, 9)
stores data shape: (1115, 10)

In [5]:
#sales data sample: S Rows
sales_df.sample(5)

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
175527,473,2,2015-02-24,2954,481,1,0,0,0
184220,246,1,2015-02-16,8884,1092,1,1,0,0
578158,259,3,2014-01-29,11005,2328,1,0,0,0
699033,714,7,2013-10-13,0,0,0,0,0,0
524640,261,2,2014-03-18,16167,1060,1,1,0,0

In [6]:
#store data sample: S Rows
stores_df.sample(5)

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
1053,1054,a,c,13190.0,NaN,NaN,1,45.0,2013.0,"Feb,May,Aug,Nov"
554,555,d,a,1560.0,1.0,2014.0,1,10.0,2013.0,"Mar,Jun,Sept,Dec"
553,554,c,c,1200.0,NaN,NaN,0,NaN,NaN,NaN
980,981,d,c,2620.0,11.0,2002.0,0,NaN,NaN,NaN
512,513,a,a,400.0,8.0,2013.0,0,NaN,NaN,NaN

In [7]:
# merging sales dataframe and store dataframe
df = pd.merge(sales_df, stores_df, on='Store',how='left')
df

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,5,2015-07-31,5263,555,1,1,0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,5,2015-07-31,6064,625,1,1,0,1,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,5,2015-07-31,8314,821,1,1,0,1,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,5,2015-07-31,13995,1498,1,1,0,1,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,5,2015-07-31,4822,559,1,1,0,1,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1017204,1111,2,2013-01-01,0,0,0,0,a,1,a,a,1900.0,6.0,2014.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
1017205,1112,2,2013-01-01,0,0,0,0,a,1,c,c,1880.0,4.0,2006.0,0,NaN,NaN,NaN
1017206,1113,2,2013-01-01,0,0,0,0,a,1,a,c,9260.0,NaN,NaN,0,NaN,NaN,NaN
1017207,1114,2,2013-01-01,0,0,0,0,a,1,a,c,870.0,NaN,NaN,0,NaN,NaN,NaN
1017208,1115,2,2013-01-01,0,0,0,0,a,1,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"

In [8]:
df.head(5)

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,5,2015-07-31,5263,555,1,1,0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,5,2015-07-31,6064,625,1,1,0,1,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,5,2015-07-31,8314,821,1,1,0,1,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,5,2015-07-31,13995,1498,1,1,0,1,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,5,2015-07-31,4822,559,1,1,0,1,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 18 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Date                       1017209 non-null  object
 3   Sales                      1017209 non-null  int64
 4   Customers                  1017209 non-null  int64
 5   Open                       1017209 non-null  int64
 6   Promo                      1017209 non-null  int64
 7   StateHoliday               1017209 non-null  object
 8   SchoolHoliday              1017209 non-null  int64
 9   StoreType                  1017209 non-null  object
 10  Assortment                 1017209 non-null  object
 11  CompetitionDistance        1014567 non-null  float64
 12  CompetitionOpenSinceMonth  693861 non-null   float64
 13  CompetitionOpenSinceYear   693861 non-null   float64
 14  Promo2                     1017209 non-null  int64
 15  Promo2SinceWeek            509178 non-null   float64
 16  Promo2SinceYear            509178 non-null   float64
 17  PromoInterval              509178 non-null   object
dtypes: float64(5), int64(8), object(5)
memory usage: 139.7+ MB

In [10]:
def convert_dtypes(df:pd.DataFrame,col:str, dtype=None, inplace:bool=False):
    try:
        if not dtype:
            print("data-type not defined")
        if col not in df.columns:
            print(f"{col} is not present in the given dataframe. the present columns are:{df.columns}")
        if inplace:
            df[col]=df[col].astype(dtype)
            print("datatype successfully changed....")
        else:
            return df[col].astype(dtype)
    except Exception as e:
        print(f"Got exception while changing dtype: {e}")

#convert_dtypes(df,'Store','int16',inplace=True)
#convert_dtypes(df,'Store','int16',inplace=False)

In [11]:
convert_dtypes(df,'Store','int16',inplace=True)
convert_dtypes(df,'DayOfWeek','int8',inplace=True)
convert_dtypes(df,'Date','datetime64[ns]' ,inplace=True)

datatype successfully changed....
datatype successfully changed....
datatype successfully changed....

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 18 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int16
 1   DayOfWeek                  1017209 non-null  int8
 2   Date                       1017209 non-null  datetime64[ns]
 3   Sales                      1017209 non-null  int64
 4   Customers                  1017209 non-null  int64
 5   Open                       1017209 non-null  int64
 6   Promo                      1017209 non-null  int64
 7   StateHoliday               1017209 non-null  object
 8   SchoolHoliday              1017209 non-null  int64
 9   StoreType                  1017209 non-null  object
 10  Assortment                 1017209 non-null  object
 11  CompetitionDistance        1014567 non-null  float64
 12  CompetitionOpenSinceMonth  693861 non-null   float64
 13  CompetitionOpenSinceYear   693861 non-null   float64
 14  Promo2                     1017209 non-null  int64
 15  Promo2SinceWeek            509178 non-null   float64
 16  Promo2SinceYear            509178 non-null   float64
 17  PromoInterval              509178 non-null   object
dtypes: datetime64[ns](1), float64(5), int16(1), int64(6), int8(1), object(4)
memory usage: 127.1+ MB

In [13]:
df[df['CompetitionDistance'].isnull()]

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
290,291,5,2015-07-31,10052,973,1,1,0,1,d,a,NaN,NaN,NaN,0,NaN,NaN,NaN
621,622,5,2015-07-31,6306,540,1,1,0,1,a,c,NaN,NaN,NaN,0,NaN,NaN,NaN
878,879,5,2015-07-31,6000,466,1,1,0,0,d,a,NaN,NaN,NaN,1,5.0,2013.0,"Feb,May,Aug,Nov"
1405,291,4,2015-07-30,9030,883,1,1,0,1,d,a,NaN,NaN,NaN,0,NaN,NaN,NaN
1736,622,4,2015-07-30,5412,406,1,1,0,1,a,c,NaN,NaN,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015601,622,3,2013-01-02,4080,451,1,0,0,1,a,c,NaN,NaN,NaN,0,NaN,NaN,NaN
1015858,879,3,2013-01-02,3077,326,1,0,0,1,d,a,NaN,NaN,NaN,1,5.0,2013.0,"Feb,May,Aug,Nov"
1016385,291,2,2013-01-01,0,0,0,0,a,1,d,a,NaN,NaN,NaN,0,NaN,NaN,NaN
1016716,622,2,2013-01-01,0,0,0,0,a,1,a,c,NaN,NaN,NaN,0,NaN,NaN,NaN
1016973,879,2,2013-01-01,0,0,0,0,a,1,d,a,NaN,NaN,NaN,1,5.0,2013.0,"Feb,May,Aug,Nov"

In [14]:
from typing import Literal
def fill_missing_values(df:pd.DataFrame, col:str, inplace:bool=False,stratagy: Literal ['mean',"median","mode","const"]='mean',const_value=None):
    try:
        #df = df.copy()
        if col not in df.columns:
            print(f"{col} is not present in the given dataframe. the present columns are:{df.columns}")
        if stratagy in ('mean','median','mode','const'):
            if stratagy.lower()=='mean':
                df[col]=df[col].fillna(df[col].mean())
                return df[col]
            elif stratagy.lower()=='median':
                df[col]=df[col].fillna(df[col].median())
                return df[col]
            elif stratagy.lower()=='mode':
                df[col]=df[col].fillna(df[col].mode()[0])
                return df[col]
            elif stratagy.lower()=='const':
                 if not const_value:
                    print("You must provide a constant value.")
                 else:
                    df[col] = df[col].fillna(const_value)
                    return df[col]
                    
            print("missing value successfully filled...")
    except Exception as e:
        print("Got exception while changing dtypes :{e}")

In [15]:
fill_missing_values(df, 'CompetitionDistance', inplace=True).isnull().sum()

np.int64(0)

In [16]:
#dictionary
d = {"Store":"int16",
     "DayOfWeek": "int8",          
     "Date":"datetime64[ns]",
     "Sales":"int16",        
     "Customers":"int8",         
     "Open":"int8",         
     "Promo": "int8",        
     "StateHoliday":"category",       
     "SchoolHoliday":"int8",         
     "StoreType":"category",        
     "Assortment":"category",        
     "CompetitionDistance":"float32",       
     "CompetitionOpenSinceMonth":"Int16",       
     "CompetitionOpenSinceYear":"Int16",       
     "Promo2":"int8",         
     "Promo2SinceWeek":"Int16" ,      
     "Promo2SinceYear":"Int16",       
     "PromoInterval":"string"
}
for key , val in d.items():
     convert_dtypes(df, key, val, inplace=True)

datatype successfully changed....
datatype successfully changed....
datatype successfully changed....
datatype successfully changed....
datatype successfully changed....
datatype successfully changed....
datatype successfully changed....
datatype successfully changed....
datatype successfully changed....
datatype successfully changed....
datatype successfully changed....
datatype successfully changed....
datatype successfully changed....
datatype successfully changed....
datatype successfully changed....
datatype successfully changed....
datatype successfully changed....
datatype successfully changed....

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 18 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int16
 1   DayOfWeek                  1017209 non-null  int8
 2   Date                       1017209 non-null  datetime64[ns]
 3   Sales                      1017209 non-null  int16
 4   Customers                  1017209 non-null  int8
 5   Open                       1017209 non-null  int8
 6   Promo                      1017209 non-null  int8
 7   StateHoliday               1017209 non-null  category
 8   SchoolHoliday              1017209 non-null  int8
 9   StoreType                  1017209 non-null  category
 10  Assortment                 1017209 non-null  category
 11  CompetitionDistance        1017209 non-null  float32
 12  CompetitionOpenSinceMonth  693861 non-null   Int16
 13  CompetitionOpenSinceYear   693861 non-null   Int16
 14  Promo2                     1017209 non-null  int8
 15  Promo2SinceWeek            509178 non-null   Int16
 16  Promo2SinceYear            509178 non-null   Int16
 17  PromoInterval              509178 non-null   string
dtypes: Int16(4), category(3), datetime64[ns](1), float32(1), int16(2), int8(6), string(1)
memory usage: 43.7 MB

In [ ]:
df.isnull().sum()

In [ ]:
sns.heatmap(df.isnull())

In [ ]:
df

In [ ]:
#handle missing values 
df['CompetitionDistance']=df['CompetitionDistance'].fillna(-1) 
df['CompetitionOpenSinceMonth']=df['CompetitionOpenSinceMonth'].fillna(-1)	
fill_missing_values(df,'CompetitionOpenSinceYear',stratagy='const', const_value=-1)
fill_missing_values(df,'Promo2SinceWeek',stratagy='const', const_value=-1)
fill_missing_values(df,'Promo2SinceYear',stratagy='const', const_value=-1)
fill_missing_values(df,'PromoInterval',stratagy='const', const_value='unk')

In [ ]:
df.info()

In [ ]:
df=df[df['Open']==1].drop(columns='Open')
df

In [ ]:
df = df[df['Sales']>0].copy()
df

In [ ]:
#reseting index
df.reset_index(drop=True,inplace=True)
df